[tool.poetry]
name = "rusty-python"
version = "0.1.0"
description = ""
authors = ["abhi3700 <dalvath3700@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
